language = {
    'en': {
        'start': 'Start Game',
        'start_webcam': 'Start Game & Use Webcam',
        'language': 'Till Svenska',
        'rock': 'Rock',
        'paper': 'Paper',
        'scissors': 'Scissors',
        'predict':'Predict',
        'predict_again':'Predict Again',
        'stop_game':'Stop game',
        'continue_game':'Continue Game',
        'choice_footer_label':'Choose An Option To Play Against The Computer',
        'cam_footer_label':'Press Predict & Gesture Rock, Paper or Scissors towards the camera',
        'human':'Human',
        'computer':'Computer',
        'score_text':'Score',
        'predicted':'Predicted',
        'prediction_continue':'Continue with Prediction',
        'round_result_Draw':'Draw',
        'round_result_human':'Human wins the round.',
        'round_result_computer':'Computer wins the round.',
        'game_result_Draw':'Game is a draw.',
        'game_result_human':'Human wins the game.',
        'game_result_computer':'Computer wins the game.',
        'cam_help':'Recommended gestures for webcam'
    },
    'sv': {
        'start': 'Starta spelet',
        'start_webcam': 'Starta spel och använd webbkamera',
        'language': 'To English',
        'rock': 'Sten',
        'paper': 'Papper',
        'scissors': 'Sax',
        'predict':'Förutse',
        'predict_again':'Förutse igen',
        'stop_game':'Stoppa spelet',
        'continue_game':'Fortsätt spelet',
        'choice_footer_label':'Välj ett alternativ att spela mot datorn',
        'cam_footer_label':'Tryck på Predict & Gesture Rock, Paper eller Sax mot kameran',
        'human':'Mänsklig',
        'computer':'Dator',
        'score_text':'Göra',
        'predicted':'Förutspådd',
        'prediction_continue':'Fortsätt med Prediction',
        'round_result_Draw':'Dra',
        'round_result_human':'Human vinner omgången.',
        'round_result_computer':'Dator vinner omgången.',
        'game_result_Draw':'Spelet är oavgjort.',
        'game_result_human':'Human vinner spelet.',
        'game_result_computer':'Dator vinner spelet.',
        'cam_help':'Rekommenderade gester för webbkamera'
    }
}